server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: khope-tp-secret-key-must-be-at-least-256-bits-long-for-hs256
  access-expiration: 3600000   # 1 hour
  refresh-expiration: 604800000 # 7 days
